# Starting the script of with every acronym out of the CompTia network pdf file we found online

acronym_dict = {
    'A': 'Address',
    'AAA': 'Authentication, Authorization and Accounting',
    'BNC': 'British Naval Connector or Bayonet Neill-Concelman',
    'ABR': 'Area Border Router',
    'ACL': 'Access Control List',
    'AD': 'Active Directory',
    'ADSL': 'Asymmetric Digital Subscriber Line',
    'AES': 'Advanced Encryption Standard',
    'AH': 'Authentication Header',
    'AP': 'Access Point',
    'APC': 'Angle Polished Connector',
    'APIPA': 'Automatic Private Internet Protocol Addressing',
    'APT': 'Advanced Persistent Protocol',
    'ARIN': 'American Registry for Internet Numbers',
    'ARP': 'Address Resolution Protocol',
    'AS': 'Autonomous System',
    'ASIC': 'Application Specific Integrated Circuit',
    'ASP': 'Application Service Provider',
    'ATM': 'Asynchronous Transfer Mode',
    'AUI': 'Attachment Unit Interface',
    'AUP': 'Acceptable Use Policy',
    'BCP': 'Business Continuity Plan',
    'BCS': 'Business Connectivity Services',
    'BDR': 'Backup Designated Router',
    'BERT': 'Bit Error Rate Test',
    'BGP': 'Border Gateway Protocol',
    'BLE': 'Bluetooth Low Energy',
    'BootP': 'Boot Protocol or Bootstrap Protocol',
    'BPDU': 'Bridge Protocol Data Unit',
    'BRI': 'Basic Rate Interface',
    'BSSID': 'Basic Service Set Identifier',
    'BYOD': 'Bring Your Own Device',
    'CAM': 'Channel Access Method',
    'CAN': 'Campus Area Network',
    'CARP': 'Common Address Redundancy Protocol',
    'CAT': 'Computer And Telephone',
    'CCTV': 'Closed Circuit TV',
    'CDMA': 'Code Division Multiple Access',
    'CDMA/CD': 'Carrier Sense Multiple Access/Collision Detection',
    'CHAP': 'Challenge Handshake Authentication Protocol',
    'CIDR': 'Classless Inter-Domain Routing',
    'CIFS': 'Common Internet File System/Services',
    'CLI': 'Command Line Interface',
    'CNAME': 'Canonical Name',
    'COOP': 'Concurrent Object-Oriented Programming',
    'COS': 'Class Of Service',
    'CPU': 'Central Processing Unit',
    'CRAM': 'Challenge-Response Authentication Mechanism–Message Digest 5',
    'CRC': 'Cyclic Redundancy Checking',
    'CSMA/CA': 'Carrier Sense Multiple Access/Collision Avoidance',
    'CSU': 'Channel Service Unit',
    'CWDM': 'Course Wave Division Multiplexing',
    'dB': 'Decibels',
    'DCS': 'Distributed Computer System',
    'DDoS': 'Distributed Denial of Service',
    'DHCP': 'Dynamic Host Configuration Protocol',
    'DLC': 'Data Link Control',
    'DLP': 'Data Leak Prevention',
    'DLR': 'Device Level Ring',
    'DMZ': 'Demilitarized Zone',
    'DNAT': 'Destination Network Address Translation',
    'DNS': 'Domain Name Service',
    'DOCSIS': 'Data-Over-Cable Service Interface Specification',
    'DoS': 'Denial of Service',
    'DR': 'Designated Router',
    'DSCP': 'Differentiated Services Code Point',
    'DSL': 'Digital Subscriber Line',
    'DSSS': 'Direct Sequence Spread Spectrum',
    'DSU': 'Data Service Unit',
    'DWDM': 'Dense Wavelength Division Multiplexing',
    'E1': 'E-Carrier Level 1',
    'EAP': 'Extensible Authentication Protocol',
    'EDNS': 'Extension Mechanisms for DNS',
    'EGP': 'Exterior Gateway Protocol',
    'EIA/TIA': 'Electronic Industries Alliance/ Telecommunication Industries Association',
    'EIGRP': 'Enhanced Interior Gateway Routing Protocol',
    'EMI': 'Electromagnetic Interference',
    'ESD': 'Electrostatic Discharge',
    'ESP': 'Encapsulated Security Packets',
    'ESSID': 'Extended Service Set Identifier',
    'EUI': 'Extended Unique Identifier',
    'FC': 'Fibre Channel',
    'FCS': 'Frame Check Sequence',
    'FDDI': 'Fiber Distributed Data Interface',
    'FDM': 'Frequency Division Multiplexing',
    'FHSS': 'Frequency Hopping Spread Spectrum',
    'FIPS': 'Federal Information Processing Standard',
    'FM': 'Frequency Modulation',
    'FQDN': 'Fully Qualified Domain Name',
    'FTP': 'File Transfer Protocol',
    'FTPS': 'File Transfer Protocol Security',
    'GBIC': 'Gigabit Interface Converter',
    'Gbps': 'Gigabits per second',
    'GLBP': 'Gateway Load Balancing Protocol',
    'GPG': 'GNU Privacy Guard',
    'GPRS': 'General Packet Radio Service',
    'GRE': 'Generic Routing Encapsulation',
    'GSM': 'Global System for Mobile communications',
    'HBA': 'Host Bus Adapter',
    'HDLC': 'High-level Data Link Control',
    'HDMI': 'High Definition Multimedia Interface',
    'HIDS': 'Host Intrusion Detection System',
    'HIPS': 'Host Intrusion Prevention System',
    'HSPA': 'High-Speed Packet Access',
    'HSRP': 'Hot Standby Router Protocol',
    'HT': 'High Throughput',
    'HTTP': 'Hypertext Transfer Protocol',
    'HTTPS': 'Hypertext Transfer Protocol Secure',
    'HVAC': 'Heating, Ventilation and Air Conditioning',
    'Hz': 'Hertz',
    'IaaS': 'Infrastructure as a Service',
    'IANA': 'Internet Assigned Numbers Authority',
    'ICA': 'Independent Computer Architecture',
    'ICANN': 'Internet Corporation for Assigned Names and Numbers',
    'ICMP': 'Internet Control Message Protocol',
    'ICS': 'Internet Connection Sharing',
    'IDF': 'Intermediate Distribution Frame',
    'IDS': 'Intrusion Detection System',
    'IEEE': 'Institute of Electrical and Electronics Engineers',
    'IGMP': 'Internet Group Multicast Protocol',
    'IGP': 'Interior Gateway Protocol',
    'IGRP': 'Interior Gateway Routing Protocol',
    'IKE': 'Internet Key Exchange',
    'IMAP4': 'Internet Message Access Protocol version 4',
    'InterNIC': 'Internet Network Information Center',
    'IO': 'Input/Output',
    'IP': 'Internet Protocol',
    'IPS': 'Intrusion Prevention System',
    'IPSec': 'Internet Protocol Security',
    'IPv4': 'Internet Protocol version 4',
    'IPv6': 'Internet Protocol version 6',
    'IR': 'Infrared',
    'ISAKMP': 'Internet Security Association and Key Management Protocol',
    'iSCSI': 'Internet Small Computer System',
    'ISDN': 'Integrated Services Digital Network',
    'IS-IS': 'Intermediate System to Intermediate System',
    'ISP': 'Internet Service Provider',
    'IT': 'Information Technology',
    'ITS': 'Intelligent Transportation System',
    'IV': 'Initialization Vector',
    'Kbps': 'Kilobits per second',
    'KVM': 'Keyboard Video Mouse',
    'L2F': 'Layer 2 Forwarding',
    'L2TP': 'Layer 2 Tunneling Protocol',
    'LACP': 'Link Aggregation Control Protocol',
    'LAN': 'Local Area Network',
    'LC': 'Local Connector',
    'LDAP': 'Lightweight Directory Access Protocol',
    'LEC': 'Local Exchange Carrier',
    'LED': 'Light Emitting Diode',
    'LLC': 'Logical Link Control',
    'LSA': 'Link State Advertisement',
    'LTE': 'Long Term Evolution',
    'LWAPP': 'Light Weight Access Point Protocol',
    'MAC': 'Media Access Control or Medium Access Control',
    'MAN': 'Metropolitan Area Network',
    'Mbps': 'Megabits per second',
    'MBps': 'Megabytes per second',
    'MDF': 'Main Distribution Frame',
    'MDI': 'Media Dependent Interface',
    'MDIX': 'Media Dependent Interface Crossover',
    'MGCP': 'Media Gateway Control Protocol',
    'MIB': 'Management Information Base',
    'MIBS': 'Management Information Bases',
    'MIMO': 'Multiple Input, Multiple Output',
    'MLA': 'Master License Agreement',
    'MMF': 'Multimode Fiber',
    'MOA': 'Memorandum Of Agreement',
    'MOU': 'Memorandum Of Understanding',
    'MPLS': 'Multi-Protocol Label Switching',
    'MS-CHAP': 'Microsoft Challenge Handshake Authentication Protocol',
    'MSA': 'Master Service Agreement',
    'MSDS': 'Material Safety Data Sheet',
    'MT-RJ': 'Mechanical Transfer-Registered Jack',
    'MTU': 'Maximum Transmission Unit',
    'MUMIMO': 'Multiuser Multiple Input, Multiple Output',
    'MX': 'Mail Exchanger',
    'NAC': 'Network Access Control',
    'NAS': 'Network Attached Storage',
    'NAT': 'Network Address Translation',
    'NCP': 'Network Control Protocol',
    'NDR': 'Non-Delivery Receipt',
    'NetBEUI': 'Network Basic Input/Output Extended User Interface',
    'NetBIOS': 'Network Basic Input/Output System',
    'NFC': 'Near Field Communication',
    'NFS': 'Network File Service',
    'NIC': 'Network Interface Card',
    'NIDS': 'Network Intrusion Detection System',
    'NIPS': 'Network Intrusion Prevention System',
    'NIST': 'Network Information Security & Technology',
    'NIU': 'Network Interface Unit',
    'nm': 'Nanometer',
    'NMS': 'Network Management System',
    'NNTP': 'Network News Transport Protocol',
    'NTP': 'Network Time Protocol',
    'OCx': 'Optical Carrier',
    'OS': 'Operating Systems',
    'OSI': 'Open Systems Interconnect',
    'OSPF': 'Open Shortest Path First',
    'OTDR': 'Optical Time Domain Reflectometer',
    'OUI': 'Organizationally Unique Identifier',
    'P2P': 'Peer-to-Peer',
    'PaaS': 'Platform as a Service',
    'PAN': 'Personal Area Network',
    'PAP': 'Password Authentication Protocol',
    'PAT': 'Port Address Translation',
    'PBX': 'Private Branch Exchange',
    'PC': 'Personal Computer',
    'PCM': 'Phase Change Memory',
    'PDU': 'Protocol Data Unit',
    'PGP': 'Pretty Good Privacy',
    'PKI': 'Public Key Infrastructure',
    'PLC': 'Programmable Logic Controller',
    'PoE': 'Power over Ethernet',
    'POP': 'Post Office Protocol',
    'POP3': 'Post Office Protocol version 3',
    'POTS': 'Plain Old Telephone System',
    'PPP': 'Point-to-Point Protocol',
    'PPPoE': 'Point-to-Point Protocol over Ethernet',
    'PPTP': 'Point-to-Point Tunneling Protocol',
    'PRI': 'Primary Rate Interface',
    'PSK': 'Pre-Shared Key',
    'PSTN': 'Public Switched Telephone Network',
    'PTP': 'Point-to-Point',
    'PTR': 'Pointer',
    'PVC': 'Permanent Virtual Circuit',
    'QAM': 'Quadrature Amplitude Modulation',
    'QoS': 'Quality of Service',
    'RADIUS': 'Remote Authentication Dial-In User Service',
    'RARP': 'Reverse Address Resolution Protocol',
    'RAS': 'Remote Access Service',
    'RDP': 'Remote Desktop Protocol',
    'RDS': 'Radio Data System',
    'RF': 'Radio Frequency',
    'RFI': 'Radio Frequency Interference',
    'RFID': 'Radio Frequency Identification',
    'RG': 'Radio Guide',
    'RIP': 'Routing Internet Protocol',
    'RJ': 'Registered Jack',
    'RPO': 'Recovery Point Objective'
}


def network():  # function named network calling network will start this function to provide the extended version of an acronym founded in the dictionary if their is not one found
                # the function will prompt the user to input the acronym into the dictionary 
    while True:
        print('Please Enter A Networking or Security Related Acronym To Get Started:\n (blank to quit) ') # prompts the user to input a networking acronym then checks to see
        acronym = input().upper() # .upper makes it so if the user inputs lower case the script will input it into uppercase 
        if acronym == '': # if the user enters nothing the loop will break
            break

        if acronym in acronym_dict:
            print(acronym_dict[acronym] + ' is the acronym of ' + acronym) # if the acronym that the user inputs matches one inside the dictionary the script will output that
            break
        try:
            print('I do not have an acronym stored for that ') 
            print('Re-Enter the acronym ?')# if their is not a acronym found in the dictionary this is the part of the script that starts to prompt the user to enter new key and key pair
            key = input().upper() 
        except KeyboardInterrupt: # Exception handling if the user decided to ctrl+c to cancel out of the script
            pass # this will pass the exception and continue on with the loop
        try:
            print("What is the acronym's definition") # asking the user what the definition for the acronym is
            value = input()
        except KeyboardInterrupt: # Exception handling like above to prevent from the user ctr+c out of the script and to continue on with the script
            pass
            acronym_dict.update({key: value}) # updates the dictionary with the key and key pair in the dictionary
            print('Acronym database updated.')
            continue # This will loop back to the beginning prompting the user to input an acronym if the user chooses to thats where they can leave the prompt blank to quit


network() # Calling the function

